name: Sign up test

on:
  push:
    branches:
      - main

jobs:
  sign_up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install selenium
        run: pip install pytest
      - name: Run test
        run: pytest test_sign_up.py
