name: Sign up 

on:
  push:
    branches:
      - main

jobs:
  sign_up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install selenium
        run: pip install selenium
      - name: Install pytest
        run: pip install pytest
      - name: install chrome driver
        run: tar https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
      - name: unzip
        run: unzip chromedriver_linux64.zip
      - name: chmod
        run: chmod +x chromedriver
      
      #still has to update
      #- name: Run test
       # run: pytest test_signup.py
